### ISSUE TITLE
Seems InGameInfo is not compatible with TFC anymore

### ISSUE THREAD

**Issue by Nagapito** [Lunatrius/InGame-Info-XML#28]
Using TFC 0.79.24 in TechNodefirmaCraft and I get this error when I had InGameInfoXml:

```
java.lang.NoSuchMethodError: com.bioxx.tfc.api.SkillsManager.getSkillsArray()Ljava/util/ArrayList;
[03/10/2015 01:03:10 AM] 	at com.github.lunatrius.ingameinfo.integration.terrafirmacraft.tag.TagTerraFirmaCraft.register(TagTerraFirmaCraft.java:211) ~[TagTerraFirmaCraft.class:?]
[03/10/2015 01:03:10 AM] 	at com.github.lunatrius.ingameinfo.integration.terrafirmacraft.TerraFirmaCraft.load(TerraFirmaCraft.java:27) ~[TerraFirmaCraft.class:?]
[03/10/2015 01:03:10 AM] 	at com.github.lunatrius.ingameinfo.integration.PluginLoader.postInit(PluginLoader.java:60) ~[PluginLoader.class:?]
[03/10/2015 01:03:10 AM] 	at com.github.lunatrius.ingameinfo.proxy.ClientProxy.postInit(ClientProxy.java:59) ~[ClientProxy.class:?]
[03/10/2015 01:03:10 AM] 	at com.github.lunatrius.ingameinfo.InGameInfoXML.postInit(InGameInfoXML.java:44) ~[InGameInfoXML.class:?]
```

**Comment by Lunatrius** [comment]
> 0.79.23 breaks compatibility with the majority of TFC addons. Either uninstall all addons, or wait to update TFC until the addons you use are updated to be compatible with 0.79.23+

Did the game crash or was that just a logged error?

**Comment by Nagapito** [comment]
It crash when launching minecraft

**Comment by Lunatrius** [comment]
Fixed the integration, latest build should work with TFC 0.79.23+ (incompatible with older versions).

**Comment by Nagapito** [comment]
Yep, working flawlessly :)
